fix(deps): update dependency @whatwg-node/fetch to v0.10.13 (#773)
This PR contains the following updates:

| Package | Change |
[Age](https://docs.renovatebot.com/merge-confidence/) |
[Confidence](https://docs.renovatebot.com/merge-confidence/) |
|---|---|---|---|
| [@whatwg-node/fetch](https://redirect.github.com/ardatan/whatwg-node)
([source](https://redirect.github.com/ardatan/whatwg-node/tree/HEAD/packages/fetch))
| [`0.9.21` ->
`0.10.13`](https://renovatebot.com/diffs/npm/@whatwg-node%2ffetch/0.9.21/0.10.13)
|
![age](https://developer.mend.io/api/mc/badges/age/npm/@whatwg-node%2ffetch/0.10.13?slim=true)
|
![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@whatwg-node%2ffetch/0.9.21/0.10.13?slim=true)
|

---

<details>
<summary>ardatan/whatwg-node (@&#8203;whatwg-node/fetch)</summary>

[`v0.10.13`](https://redirect.github.com/ardatan/whatwg-node/blob/HEAD/packages/fetch/CHANGELOG.md#01013)

[Compare
Source](https://redirect.github.com/ardatan/whatwg-node/compare/@whatwg-node/fetch@0.10.12...@whatwg-node/fetch@0.10.13)

-
[#&#8203;2910](https://redirect.github.com/ardatan/whatwg-node/pull/2910)

[`0079afd`](https://redirect.github.com/ardatan/whatwg-node/commit/0079afdc785c012fad22dd35963800a8199bfe89)
Thanks [@&#8203;ardatan](https://redirect.github.com/ardatan)! -
Zstandard \`zstd\` support

- Updated dependencies

\[[`0079afd`](https://redirect.github.com/ardatan/whatwg-node/commit/0079afdc785c012fad22dd35963800a8199bfe89)]:
-
[@&#8203;whatwg-node/node-fetch](https://redirect.github.com/whatwg-node/node-fetch)@&#8203;0.8.3

[`v0.10.12`](https://redirect.github.com/ardatan/whatwg-node/blob/HEAD/packages/fetch/CHANGELOG.md#01012)

[Compare
Source](https://redirect.github.com/ardatan/whatwg-node/compare/@whatwg-node/fetch@0.10.11...@whatwg-node/fetch@0.10.12)

-
[`c9b2c87`](https://redirect.github.com/ardatan/whatwg-node/commit/c9b2c87bff6f36b71cd1bd97f81f1050efa8dd98)
Thanks [@&#8203;ardatan](https://redirect.github.com/ardatan)! - Do not
override existing \`user-agent\`

- Updated dependencies

\[[`c9b2c87`](https://redirect.github.com/ardatan/whatwg-node/commit/c9b2c87bff6f36b71cd1bd97f81f1050efa8dd98)]:
-
[@&#8203;whatwg-node/node-fetch](https://redirect.github.com/whatwg-node/node-fetch)@&#8203;0.8.2

[`v0.10.11`](https://redirect.github.com/ardatan/whatwg-node/blob/HEAD/packages/fetch/CHANGELOG.md#01011)

[Compare
Source](https://redirect.github.com/ardatan/whatwg-node/compare/@whatwg-node/fetch@0.10.10...@whatwg-node/fetch@0.10.11)

- Updated dependencies

\[[`60d41d6`](https://redirect.github.com/ardatan/whatwg-node/commit/60d41d6df941ca16f733556a3d3586486236a146)]:
-
[@&#8203;whatwg-node/node-fetch](https://redirect.github.com/whatwg-node/node-fetch)@&#8203;0.8.0

[`v0.10.10`](https://redirect.github.com/ardatan/whatwg-node/blob/HEAD/packages/fetch/CHANGELOG.md#01010)

[Compare
Source](https://redirect.github.com/ardatan/whatwg-node/compare/@whatwg-node/fetch@0.10.9...@whatwg-node/fetch@0.10.10)

-
[#&#8203;2656](https://redirect.github.com/ardatan/whatwg-node/pull/2656)

[`d2ef55c`](https://redirect.github.com/ardatan/whatwg-node/commit/d2ef55c7735c7127e4ed404dd8bbebe8fd3ebd00)
Thanks [@&#8203;renovate](https://redirect.github.com/apps/renovate)! -
Fix TypeScript issues and bump the version
  to get performance improvements for all dependent packages
- Updated dependencies

\[[`d2ef55c`](https://redirect.github.com/ardatan/whatwg-node/commit/d2ef55c7735c7127e4ed404dd8bbebe8fd3ebd00)]:
-
[@&#8203;whatwg-node/node-fetch](https://redirect.github.com/whatwg-node/node-fetch)@&#8203;0.7.25

[`v0.10.9`](https://redirect.github.com/ardatan/whatwg-node/blob/HEAD/packages/fetch/CHANGELOG.md#0109)

[Compare
Source](https://redirect.github.com/ardatan/whatwg-node/compare/@whatwg-node/fetch@0.10.8...@whatwg-node/fetch@0.10.9)

-
[#&#8203;2553](https://redirect.github.com/ardatan/whatwg-node/pull/2553)

[`752b0eb`](https://redirect.github.com/ardatan/whatwg-node/commit/752b0ebdc88654ef4ae1e13eb860980f437b4110)
Thanks [@&#8203;renovate](https://redirect.github.com/apps/renovate)! -
Fix the conflict of urlpattern-ponyfill
  and \`@types/node\`

- Updated dependencies

\[[`b69157b`](https://redirect.github.com/ardatan/whatwg-node/commit/b69157bd97aba8fb4c761f8d16afc549c35acfa0)]:
-
[@&#8203;whatwg-node/node-fetch](https://redirect.github.com/whatwg-node/node-fetch)@&#8203;0.7.22

[`v0.10.8`](https://redirect.github.com/ardatan/whatwg-node/blob/HEAD/packages/fetch/CHANGELOG.md#0108)

[Compare
Source](https://redirect.github.com/ardatan/whatwg-node/compare/@whatwg-node/fetch@0.10.7...@whatwg-node/fetch@0.10.8)

-
[#&#8203;2424](https://redirect.github.com/ardatan/whatwg-node/pull/2424)

[`28c4ad9`](https://redirect.github.com/ardatan/whatwg-node/commit/28c4ad98aad3ec95a1f0893c54f5484d8564f675)
Thanks [@&#8203;ardatan](https://redirect.github.com/ardatan)! -
Performance optimizations
- Avoid creating `AbortController` and `AbortSignal` if not needed with
`new Request` because it
    is expensive
- Avoid creating a map for `Headers` and try to re-use the init object
for `Headers` for
    performance with a single-line `writeHead`.
  - Avoid creating `Buffer` for `string` bodies for performance
- Use `setHeaders` which accepts `Headers` since Node 18 if needed to
forward `Headers` to Node

- Updated dependencies

\[[`28c4ad9`](https://redirect.github.com/ardatan/whatwg-node/commit/28c4ad98aad3ec95a1f0893c54f5484d8564f675)]:
-
[@&#8203;whatwg-node/node-fetch](https://redirect.github.com/whatwg-node/node-fetch)@&#8203;0.7.21

[`v0.10.7`](https://redirect.github.com/ardatan/whatwg-node/blob/HEAD/packages/fetch/CHANGELOG.md#0107)

[Compare
Source](https://redirect.github.com/ardatan/whatwg-node/compare/@whatwg-node/fetch@0.10.6...@whatwg-node/fetch@0.10.7)

-
[#&#8203;2383](https://redirect.github.com/ardatan/whatwg-node/pull/2383)

[`9527e8f`](https://redirect.github.com/ardatan/whatwg-node/commit/9527e8fe2dc73e362b38060f4a6decbb87a4f597)
Thanks [@&#8203;ardatan](https://redirect.github.com/ardatan)! - Some
implementations like `compression` npm
package do not implement `response.write(data, callback)` signature, but
whatwg-node/server waits
for it to finish the response stream. Then it causes the response stream
hangs when the
compression package takes the stream over when the response data is
larger than its threshold.

  It is actually a bug in `compression` package;

[expressjs/compression#46](https://redirect.github.com/expressjs/compression/issues/46)
But since it is a
  common mistake, we prefer to workaround this on our end.

Now after calling `response.write`, it no longer uses callback but first
it checks the result;

if it is `true`, it means stream is drained and we can call
`response.end` immediately. else if it
is `false`, it means the stream is not drained yet, so we can wait for
the `drain` event to call
  `response.end`.

- Updated dependencies

\[[`9527e8f`](https://redirect.github.com/ardatan/whatwg-node/commit/9527e8fe2dc73e362b38060f4a6decbb87a4f597)]:
-
[@&#8203;whatwg-node/node-fetch](https://redirect.github.com/whatwg-node/node-fetch)@&#8203;0.7.19

[`v0.10.6`](https://redirect.github.com/ardatan/whatwg-node/blob/HEAD/packages/fetch/CHANGELOG.md#0106)

[Compare
Source](https://redirect.github.com/ardatan/whatwg-node/compare/@whatwg-node/fetch@0.10.5...@whatwg-node/fetch@0.10.6)

-
[#&#8203;2310](https://redirect.github.com/ardatan/whatwg-node/pull/2310)

[`f699a1b`](https://redirect.github.com/ardatan/whatwg-node/commit/f699a1ba1558f98406f5844a31c07f77d874eb9b)
Thanks [@&#8203;enisdenjo](https://redirect.github.com/enisdenjo)! -
dependencies updates:
  - Updated dependency
[`@whatwg-node/node-fetch@^0.7.18`
↗︎](https://www.npmjs.com/package/@&#8203;whatwg-node/node-fetch/v/0.7.18)
    (from `^0.7.11`, in `dependencies`)

[`v0.10.5`](https://redirect.github.com/ardatan/whatwg-node/blob/HEAD/packages/fetch/CHANGELOG.md#0105)

[Compare
Source](https://redirect.github.com/ardatan/whatwg-node/compare/@whatwg-node/fetch@0.10.4...@whatwg-node/fetch@0.10.5)

-
[#&#8203;2093](https://redirect.github.com/ardatan/whatwg-node/pull/2093)

[`31f021a`](https://redirect.github.com/ardatan/whatwg-node/commit/31f021ac5df1ddd7f16807d4ed6c5776d250ab29)
Thanks [@&#8203;ardatan](https://redirect.github.com/ardatan)! - Fixes
the
`TypeError: bodyInit.stream is not a function` error thrown when
`@whatwg-node/server` is used
with `node:http2` and attempts the incoming HTTP/2 request to parse with
`Request.json`,
  `Request.text`, `Request.formData`, or `Request.blob` methods.

- Updated dependencies

\[[`31f021a`](https://redirect.github.com/ardatan/whatwg-node/commit/31f021ac5df1ddd7f16807d4ed6c5776d250ab29)]:
-
[@&#8203;whatwg-node/node-fetch](https://redirect.github.com/whatwg-node/node-fetch)@&#8203;0.7.11

[`v0.10.4`](https://redirect.github.com/ardatan/whatwg-node/blob/HEAD/packages/fetch/CHANGELOG.md#0104)

[Compare
Source](https://redirect.github.com/ardatan/whatwg-node/compare/@whatwg-node/fetch@0.10.3...@whatwg-node/fetch@0.10.4)

-
[#&#8203;2082](https://redirect.github.com/ardatan/whatwg-node/pull/2082)

[`b217e30`](https://redirect.github.com/ardatan/whatwg-node/commit/b217e305b5a5d63e164cf83ef45e7d1e95fefa0e)
Thanks [@&#8203;ardatan](https://redirect.github.com/ardatan)! -
dependencies updates:
  - Updated dependency
[`@whatwg-node/node-fetch@^0.7.9`
↗︎](https://www.npmjs.com/package/@&#8203;whatwg-node/node-fetch/v/0.7.9)
    (from `^0.7.8`, in `dependencies`)

-
[#&#8203;2079](https://redirect.github.com/ardatan/whatwg-node/pull/2079)

[`090b4b0`](https://redirect.github.com/ardatan/whatwg-node/commit/090b4b0d2aefbf36707fa236395bc6ea99227b9c)
Thanks [@&#8203;ardatan](https://redirect.github.com/ardatan)! - Fix the
bug when `set-cookies` given is ignored
  in `HeadersInit`;

  ```js
  import { Headers } from '@&#8203;whatwg-node/fetch'

  const headers = new Headers([
    ['set-cookie', 'a=b'],
    ['set-cookie', 'c=d']
  ])
expect(headers.getSetCookie()).toEqual(['a=b', 'c=d']) // Previously it
was empty
  ```

- Updated dependencies

\[[`090b4b0`](https://redirect.github.com/ardatan/whatwg-node/commit/090b4b0d2aefbf36707fa236395bc6ea99227b9c)]:
-
[@&#8203;whatwg-node/node-fetch](https://redirect.github.com/whatwg-node/node-fetch)@&#8203;0.7.10

[`v0.10.3`](https://redirect.github.com/ardatan/whatwg-node/blob/HEAD/packages/fetch/CHANGELOG.md#0103)

[Compare
Source](https://redirect.github.com/ardatan/whatwg-node/compare/@whatwg-node/fetch@0.10.2...@whatwg-node/fetch@0.10.3)

-
[#&#8203;1961](https://redirect.github.com/ardatan/whatwg-node/pull/1961)

[`2785c80`](https://redirect.github.com/ardatan/whatwg-node/commit/2785c80be2c887c581ef0fac8150befeab306eba)
Thanks [@&#8203;ardatan](https://redirect.github.com/ardatan)! -
`ReadableStream`'s `Symbol.asyncIterator` now
returns `AsyncIterableIterator` like before even if it is ok to return
`AsyncIterator` right now.
It is safer to return `AsyncIterableIterator` because it is a common
mistake to use
  `AsyncIterator` as `AsyncIterable`.
- Updated dependencies

\[[`2785c80`](https://redirect.github.com/ardatan/whatwg-node/commit/2785c80be2c887c581ef0fac8150befeab306eba)]:
-
[@&#8203;whatwg-node/node-fetch](https://redirect.github.com/whatwg-node/node-fetch)@&#8203;0.7.7

[`v0.10.2`](https://redirect.github.com/ardatan/whatwg-node/blob/HEAD/packages/fetch/CHANGELOG.md#0102)

[Compare
Source](https://redirect.github.com/ardatan/whatwg-node/compare/@whatwg-node/fetch@0.10.1...@whatwg-node/fetch@0.10.2)

-
[#&#8203;1929](https://redirect.github.com/ardatan/whatwg-node/pull/1929)

[`b88b85c`](https://redirect.github.com/ardatan/whatwg-node/commit/b88b85c301923719f4722bdfe070728725bcc1b5)
Thanks [@&#8203;ardatan](https://redirect.github.com/ardatan)! -
dependencies updates:
  - Updated dependency
[`@whatwg-node/node-fetch@^0.7.5`
↗︎](https://www.npmjs.com/package/@&#8203;whatwg-node/node-fetch/v/0.7.5)
    (from `^0.7.1`, in `dependencies`)
- Updated dependencies

\[[`b88b85c`](https://redirect.github.com/ardatan/whatwg-node/commit/b88b85c301923719f4722bdfe070728725bcc1b5),

[`9b39c3e`](https://redirect.github.com/ardatan/whatwg-node/commit/9b39c3e5db616a60e6dd8472fbd651f4905f3673),

[`b88b85c`](https://redirect.github.com/ardatan/whatwg-node/commit/b88b85c301923719f4722bdfe070728725bcc1b5)]:
-
[@&#8203;whatwg-node/node-fetch](https://redirect.github.com/whatwg-node/node-fetch)@&#8203;0.7.6

[`v0.10.1`](https://redirect.github.com/ardatan/whatwg-node/blob/HEAD/packages/fetch/CHANGELOG.md#01011)

[Compare
Source](https://redirect.github.com/ardatan/whatwg-node/compare/@whatwg-node/fetch@0.10.0...@whatwg-node/fetch@0.10.1)

- Updated dependencies

\[[`60d41d6`](https://redirect.github.com/ardatan/whatwg-node/commit/60d41d6df941ca16f733556a3d3586486236a146)]:
-
[@&#8203;whatwg-node/node-fetch](https://redirect.github.com/whatwg-node/node-fetch)@&#8203;0.8.0

[`v0.10.0`](https://redirect.github.com/ardatan/whatwg-node/blob/HEAD/packages/fetch/CHANGELOG.md#0100)

[Compare
Source](https://redirect.github.com/ardatan/whatwg-node/compare/@whatwg-node/fetch@0.9.23...@whatwg-node/fetch@0.10.0)

-
[#&#8203;1782](https://redirect.github.com/ardatan/whatwg-node/pull/1782)

[`6c006e1`](https://redirect.github.com/ardatan/whatwg-node/commit/6c006e12eaa6705cdf20b7b43cccc44a1f7ea185)
Thanks [@&#8203;ardatan](https://redirect.github.com/ardatan)! -
\`TextDecoderStream\` and \`TextEncoderStream\`

- Updated dependencies

\[[`6c006e1`](https://redirect.github.com/ardatan/whatwg-node/commit/6c006e12eaa6705cdf20b7b43cccc44a1f7ea185)]:
-
[@&#8203;whatwg-node/node-fetch](https://redirect.github.com/whatwg-node/node-fetch)@&#8203;0.7.0

[`v0.9.23`](https://redirect.github.com/ardatan/whatwg-node/blob/HEAD/packages/fetch/CHANGELOG.md#0923)

[Compare
Source](https://redirect.github.com/ardatan/whatwg-node/compare/@whatwg-node/fetch@0.9.22...@whatwg-node/fetch@0.9.23)

- Updated dependencies

\[[`637185f`](https://redirect.github.com/ardatan/whatwg-node/commit/637185f5c992ccabff13b185d4e14f09680228da)]:
-
[@&#8203;whatwg-node/node-fetch](https://redirect.github.com/whatwg-node/node-fetch)@&#8203;0.6.0

[`v0.9.22`](https://redirect.github.com/ardatan/whatwg-node/blob/HEAD/packages/fetch/CHANGELOG.md#0922)

[Compare
Source](https://redirect.github.com/ardatan/whatwg-node/compare/@whatwg-node/fetch@0.9.21...@whatwg-node/fetch@0.9.22)

-
[`77dd1c3`](https://redirect.github.com/ardatan/whatwg-node/commit/77dd1c3acde29aeb828b6eb37b6fbdbb47a16c57)
Thanks [@&#8203;ardatan](https://redirect.github.com/ardatan)! - Use
\`globalThis\` instead of \`window\` for the
  global object reference

  Fixes the issues with Deno

- Updated dependencies

\[[`9281e02`](https://redirect.github.com/ardatan/whatwg-node/commit/9281e021282a43a3dda8c8a5c9647d340b28698e)]:
-
[@&#8203;whatwg-node/node-fetch](https://redirect.github.com/whatwg-node/node-fetch)@&#8203;0.5.27

</details>

---

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about these
updates again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/cedarjs/cedar).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0Mi41OS4wIiwidXBkYXRlZEluVmVyIjoiNDIuNTkuMCIsInRhcmdldEJyYW5jaCI6Im1haW4iLCJsYWJlbHMiOlsiY2hhbmdlc2V0cy1vayIsInJlbGVhc2U6ZGVwZW5kZW5jeSJdfQ==-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>