chore(release): Fix canary release script (#1743)
Was getting this error when trying to release canary versions:

```
Run ./.github/scripts/publish_canary.sh
npm user: tobbe
NPM token for 'cedarjs' org scope is valid and not expired
Publishing canary from main using npm token npm_Z
Latest tag: create-redmix-rsc-app/v0.0.3
Commits since tag: 1776
Current version: create-redmix-rsc-app/v0.0.3
./.github/scripts/publish_canary.sh: line 136: create: unbound variable
Error: Process completed with exit code 1. 
```